[package]
name = "rr-cli"
version = "0.1.0"
description = "RéseauRacine CLI — messagerie chiffrée P2P sur Nostr"
homepage.workspace = true
repository.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "rr"
path = "src/main.rs"

[dependencies]
rr-core = { path = "../rr-core" }
nostr.workspace = true
nostr-sdk.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
clap = { version = "4", features = ["derive"] }
uuid = { version = "1", features = ["v4"] }
